Solved Issue
AasthaGithub/Customizable_Portfolio pull request #81
Opened 2020-09-10 14:48 UTC by stefanuslim

## Related issue
- Clear All CheckBoxes of individual elements after "DownloadAll" button is clicked

## Proposed changes
- Using props on each related components
- When click downloadAll, all checkboxes will clear automatically

## Additional Information
- Please check the functionality or my code

Thank You

2020-09-10 19:28 UTC, AasthaGithub requested changes
Even though check box go visibly unticked, yet the state of those Elements' checkbox remains unaltered.

Possible Reasons could be: When updating state of check box, the append_Selected/ clear_selected isn't taken care of (in ElementItem: UseEffect hook)

Also, remove package-lock.json file that's committed

2020-09-11 02:47 UTC, stefanuslim commented
Hi,

Sorry I didn't check the selected_set before. Already committed changes
with clearSelected() function on useEffect hook.
Also removed the package-lock.json. Kindly check my code again.

Thank You

On Fri, Sep 11, 2020 at 2:29 AM AasthaGithub <notifications@github.com>
wrote:

> *@AasthaGithub* requested changes on this pull request.
>
> Even though check box go visibly unticked, yet the state of those
> Elements' checkbox remains unaltered.
>
> Possible Reasons could be: When updating state of check box, the
> append_Selected/ clear_selected isn't taken care of (in ElementItem:
> UseEffect hook)
>
> Also, remove package-lock.json file that's committed
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/AasthaGithub/Customizable_Portfolio/pull/81#pullrequestreview-486246723>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOIEHJY7PJT6EY2BI3EEHTTSFESIFANCNFSM4RFGKSAQ>
> .
>

2020-09-11 04:29 UTC, AasthaGithub approved these changes

2020-09-11 04:34 UTC, AasthaGithub commented
No worries, great job.✨

2020-09-11 04:36 UTC, merged